### PR TITLE
Not a real pull request

### PR DESCRIPTION
**Pull request by JaderDias**
Hello Korovkin,

I just want to let you know that your project inspired me to make my own version of it and write an article about it https://medium.com/@jaderd/you-have-to-limit-your-goroutines-if-you-want-a-reliable-aws-lambda-function-f8b8e81f56b4

### CODE REVIEW

**Comment by korovkin** [comment]
thank you for letting me know !

**Comment by korovkin** [comment]
and thank you for the article 
i just don't know why you would write your own rather than contributing to an existing version 

is there anything missing for you in this one?

**Comment by korovkin** [comment]
you literally copy pasted and forked this :) 

at least reference the original version on the main page: 
https://github.com/JaderDias/limiter

**Comment by JaderDias** [comment]
the original version is already referenced, since it's a fork. look on the upper left corner.

the core "limiter.go" file is very different between the two versions, they are incompatible

**Comment by korovkin** [comment]
i would reference if on your README.md 
but that's ok, you don't have to do it 

i am glad this was useful to you in any way or form 
cheers

**Comment by korovkin** [comment]
Should we close this PR?

**Pull request closed without merging**
